/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejerciciostaller;

import java.awt.event.KeyEvent;
import static java.lang.Integer.min;
import java.math.BigInteger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aprendiz
 */
public class ejer_4 extends javax.swing.JFrame {

    /**
     * Creates new form ejer_4
     */
    public ejer_4() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnumeroejer4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblesultadosejer4 = new javax.swing.JTextField();
        btnejer4 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        txtNumeroEjer15 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        lblResultadoEjer15 = new javax.swing.JTextField();
        btnBotonEjer15 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtFecha1Ejer8 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        lblValidacionEjer8 = new javax.swing.JTextField();
        btnValidarResultadoEjer8 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNumero1Ejer9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        lblResultadomesEjer9 = new javax.swing.JTextField();
        btnCalcularEjer9 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtNumero1Ejer10 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        lblResultadoEjer10 = new javax.swing.JTextField();
        btnCalcularEjer10 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtNumero1Ejer11 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        lblResultadoEjer11 = new javax.swing.JTextField();
        btnCalcularEjer11 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtNumero1Ejer12 = new javax.swing.JTextField();
        lblParCapicuoEjer12 = new javax.swing.JTextField();
        btnCalcularEjer12 = new javax.swing.JButton();
        lblParEjer12 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        txtDigiteEjer14 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        lblResultadoEjer14 = new javax.swing.JTextField();
        btnCalcularEjer14 = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCateto1Ejer7 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCateto2Ejer7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lblResultadoEjer7 = new javax.swing.JTextField();
        btnCalcularHipotenusaEjer7 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroEjer5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblResultadoEjer5 = new javax.swing.JTextField();
        btnCalcularEjer5 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNumero1Ejer6 = new javax.swing.JTextField();
        txtNumero2Ejer6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNumero3Ejer6 = new javax.swing.JTextField();
        btnCalcularEjer6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblResultadoEjer6 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtEjer13 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        lblResultadoejer13 = new javax.swing.JLabel();
        btnBoton = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        txtVecesEjer13 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        txtFraseEjer16 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        lblResultadoEjer16 = new javax.swing.JTextField();
        btnCalcularEjer16 = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel63.setText("jLabel63");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 204)));
        jTabbedPane1.setForeground(new java.awt.Color(0, 204, 204));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N

        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(177, 79, 0, 0);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("What time is it?", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Saber si es digito de 3 o 4");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 20, 139, 30);

        jLabel3.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>Digite un numero para saber<center> si es multiplo de 3 o de 4 ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 50, 158, 32);

        txtnumeroejer4.setForeground(new java.awt.Color(0, 0, 0));
        txtnumeroejer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroejer4ActionPerformed(evt);
            }
        });
        txtnumeroejer4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kaypreseejer4(evt);
            }
        });
        jPanel1.add(txtnumeroejer4);
        txtnumeroejer4.setBounds(220, 90, 170, 30);

        jLabel4.setFont(new java.awt.Font("Swis721 LtCn BT", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Su resultado es:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(220, 130, 90, 16);

        lblesultadosejer4.setForeground(new java.awt.Color(0, 0, 0));
        lblesultadosejer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblesultadosejer4ActionPerformed(evt);
            }
        });
        jPanel1.add(lblesultadosejer4);
        lblesultadosejer4.setBounds(208, 158, 202, 30);

        btnejer4.setText("Calcular el resultado");
        btnejer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnejer4ActionPerformed(evt);
            }
        });
        btnejer4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumeroejer4(evt);
            }
        });
        jPanel1.add(btnejer4);
        btnejer4.setBounds(440, 190, 140, 40);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciostaller/7d07a255678962d30d8717dcf5dbd266.gif"))); // NOI18N
        jLabel40.setText("jLabel40");
        jPanel1.add(jLabel40);
        jLabel40.setBounds(-10, 0, 600, 430);

        jTabbedPane1.addTab("Ejercicio 4", jPanel1);

        jPanel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyPressEjer15(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel37.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Digite el numero del 0 al 99 donde se mostrara escrito");
        jPanel4.add(jLabel37);
        jLabel37.setBounds(20, 30, 350, 50);

        jLabel55.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Digite un numero ");
        jPanel4.add(jLabel55);
        jLabel55.setBounds(20, 80, 150, 30);

        txtNumeroEjer15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyPressEjer15(evt);
            }
        });
        jPanel4.add(txtNumeroEjer15);
        txtNumeroEjer15.setBounds(20, 120, 200, 30);

        jLabel56.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Su resultado es");
        jPanel4.add(jLabel56);
        jLabel56.setBounds(20, 160, 110, 30);

        lblResultadoEjer15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblResultadoEjer15ActionPerformed(evt);
            }
        });
        jPanel4.add(lblResultadoEjer15);
        lblResultadoEjer15.setBounds(20, 200, 200, 30);

        btnBotonEjer15.setText("Calcular");
        btnBotonEjer15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotonEjer15ActionPerformed(evt);
            }
        });
        jPanel4.add(btnBotonEjer15);
        btnBotonEjer15.setBounds(350, 190, 90, 30);

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciostaller/15.1.gif"))); // NOI18N
        jPanel4.add(jLabel61);
        jLabel61.setBounds(-7, 6, 590, 380);

        jTabbedPane1.addTab("Ejercicio 15", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setForeground(new java.awt.Color(102, 102, 102));
        jPanel5.setLayout(null);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("<html>El digitar una fecha de manera ordenada<center> año, mes y dia; se valida que este en este orden   ");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(0, 0, 310, 100);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Ingrese la fecha de manera como se pide ");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(60, 120, 297, 16);

        txtFecha1Ejer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecha1Ejer8ActionPerformed(evt);
            }
        });
        txtFecha1Ejer8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Keypress1Ejer8(evt);
            }
        });
        jPanel5.add(txtFecha1Ejer8);
        txtFecha1Ejer8.setBounds(70, 140, 218, 22);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Validacion si esta en orden ");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(70, 180, 229, 16);
        jPanel5.add(lblValidacionEjer8);
        lblValidacionEjer8.setBounds(70, 210, 218, 22);

        btnValidarResultadoEjer8.setForeground(new java.awt.Color(255, 255, 255));
        btnValidarResultadoEjer8.setText("Validar");
        btnValidarResultadoEjer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarResultadoEjer8ActionPerformed(evt);
            }
        });
        jPanel5.add(btnValidarResultadoEjer8);
        btnValidarResultadoEjer8.setBounds(320, 260, 72, 23);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciostaller/8.1.gif"))); // NOI18N
        jPanel5.add(jLabel48);
        jLabel48.setBounds(0, 0, 580, 390);

        jTabbedPane1.addTab("Ejercicio 8", jPanel5);

        jPanel6.setLayout(null);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("SimSun-ExtB", 2, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("<html>Se ingresa el numero de el uno al doce <center>\n se le imprimira que mes es");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(96, 34, 380, 60);

        jLabel23.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Ingrese un numero del uno al doce");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(206, 90, 290, 19);

        txtNumero1Ejer9.setForeground(new java.awt.Color(0, 0, 0));
        txtNumero1Ejer9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Keypressejer9(evt);
            }
        });
        jPanel6.add(txtNumero1Ejer9);
        txtNumero1Ejer9.setBounds(206, 124, 184, 22);

        jLabel24.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("El valor de el mes es:");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(206, 164, 170, 19);

        lblResultadomesEjer9.setForeground(new java.awt.Color(0, 0, 0));
        lblResultadomesEjer9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblResultadomesEjer9ActionPerformed(evt);
            }
        });
        jPanel6.add(lblResultadomesEjer9);
        lblResultadomesEjer9.setBounds(206, 198, 310, 40);

        btnCalcularEjer9.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularEjer9.setText("Calcular");
        btnCalcularEjer9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularEjer9ActionPerformed(evt);
            }
        });
        jPanel6.add(btnCalcularEjer9);
        btnCalcularEjer9.setBounds(360, 270, 100, 23);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciostaller/descarga.gif"))); // NOI18N
        jPanel6.add(jLabel43);
        jLabel43.setBounds(20, -20, 590, 430);

        jTabbedPane1.addTab("Ejercicio 9 ", jPanel6);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("<html>Un numero en la cual se van a calcular que numero de horas,<center>  minutos y segundos a invertido en el examen ");
        jPanel7.add(jLabel25);
        jLabel25.setBounds(0, 10, 370, 60);

        jLabel26.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Ingrese el numero que desee calcular");
        jPanel7.add(jLabel26);
        jLabel26.setBounds(20, 80, 310, 18);

        txtNumero1Ejer10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeypressEjer10(evt);
            }
        });
        jPanel7.add(txtNumero1Ejer10);
        txtNumero1Ejer10.setBounds(10, 110, 206, 22);

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Su resultado es");
        jPanel7.add(jLabel27);
        jLabel27.setBounds(10, 150, 180, 16);

        lblResultadoEjer10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblResultadoEjer10ActionPerformed(evt);
            }
        });
        jPanel7.add(lblResultadoEjer10);
        lblResultadoEjer10.setBounds(10, 180, 365, 22);

        btnCalcularEjer10.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularEjer10.setText("Calcular");
        btnCalcularEjer10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularEjer10ActionPerformed(evt);
            }
        });
        jPanel7.add(btnCalcularEjer10);
        btnCalcularEjer10.setBounds(80, 260, 120, 23);
        jPanel7.add(jLabel45);
        jLabel45.setBounds(460, 130, 0, 0);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciostaller/6.1.gif"))); // NOI18N
        jLabel39.setText("jLabel39");
        jPanel7.add(jLabel39);
        jLabel39.setBounds(-7, 0, 590, 390);

        jTabbedPane1.addTab("Ejercicio 10", jPanel7);

        jPanel8.setBackground(new java.awt.Color(153, 51, 255));
        jPanel8.setForeground(new java.awt.Color(51, 255, 255));
        jPanel8.setLayout(null);

        jLabel28.setBackground(new java.awt.Color(0, 255, 204));
        jLabel28.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 0));
        jLabel28.setText("<html>Dar un numero y luego que se muestre<center> en orden inverso ");
        jPanel8.add(jLabel28);
        jLabel28.setBounds(20, 20, 150, 90);

        jLabel29.setBackground(new java.awt.Color(153, 255, 255));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 0, 0));
        jLabel29.setText("<html>Ingrese el numero<center> para mostar la inversa ");
        jPanel8.add(jLabel29);
        jLabel29.setBounds(30, 120, 200, 60);

        txtNumero1Ejer11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeypressEjer11(evt);
            }
        });
        jPanel8.add(txtNumero1Ejer11);
        txtNumero1Ejer11.setBounds(30, 190, 216, 22);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 0, 0));
        jLabel30.setText("Su resultado");
        jPanel8.add(jLabel30);
        jLabel30.setBounds(160, 230, 110, 25);

        lblResultadoEjer11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblResultadoEjer11ActionPerformed(evt);
            }
        });
        jPanel8.add(lblResultadoEjer11);
        lblResultadoEjer11.setBounds(20, 270, 216, 22);

        btnCalcularEjer11.setBackground(new java.awt.Color(255, 255, 255));
        btnCalcularEjer11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCalcularEjer11.setForeground(new java.awt.Color(51, 0, 0));
        btnCalcularEjer11.setText("Calcular");
        btnCalcularEjer11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularEjer11ActionPerformed(evt);
            }
        });
        jPanel8.add(btnCalcularEjer11);
        btnCalcularEjer11.setBounds(240, 330, 90, 23);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciostaller/11.11.gif"))); // NOI18N
        jLabel44.setText("jLabel44");
        jPanel8.add(jLabel44);
        jLabel44.setBounds(0, 0, 590, 410);

        jTabbedPane1.addTab("Ejercicio 11", jPanel8);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setLayout(null);

        jLabel31.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Se calcula si es par y tambien si es capicuo");
        jPanel9.add(jLabel31);
        jLabel31.setBounds(10, 20, 340, 40);
        jPanel9.add(jLabel32);
        jLabel32.setBounds(141, 66, 0, 0);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Ingrese un numero");
        jPanel9.add(jLabel33);
        jLabel33.setBounds(10, 70, 190, 16);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Saber si es par y si es capicuo");
        jPanel9.add(jLabel34);
        jLabel34.setBounds(10, 160, 200, 16);

        txtNumero1Ejer12.setBackground(new java.awt.Color(204, 255, 255));
        txtNumero1Ejer12.setForeground(new java.awt.Color(0, 0, 0));
        txtNumero1Ejer12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeypressEjer12(evt);
            }
        });
        jPanel9.add(txtNumero1Ejer12);
        txtNumero1Ejer12.setBounds(10, 100, 223, 30);

        lblParCapicuoEjer12.setBackground(new java.awt.Color(204, 255, 255));
        jPanel9.add(lblParCapicuoEjer12);
        lblParCapicuoEjer12.setBounds(10, 190, 223, 30);

        btnCalcularEjer12.setBackground(new java.awt.Color(255, 255, 255));
        btnCalcularEjer12.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcularEjer12.setText("Calcular");
        btnCalcularEjer12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularEjer12ActionPerformed(evt);
            }
        });
        jPanel9.add(btnCalcularEjer12);
        btnCalcularEjer12.setBounds(310, 210, 100, 23);

        lblParEjer12.setBackground(new java.awt.Color(204, 255, 255));
        lblParEjer12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel9.add(lblParEjer12);
        lblParEjer12.setBounds(10, 230, 230, 30);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciostaller/12.2.gif"))); // NOI18N
        jPanel9.add(jLabel41);
        jLabel41.setBounds(-150, 0, 730, 390);

        jTabbedPane1.addTab("Ejercicio 12", jPanel9);

        jPanel11.setLayout(null);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Se determina si una cadena de caracteres es palíndroma");
        jPanel11.add(jLabel36);
        jLabel36.setBounds(0, 10, 380, 40);

        jLabel53.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Digita para saber si es una cadena palindroma");
        jPanel11.add(jLabel53);
        jLabel53.setBounds(10, 60, 260, 30);

        txtDigiteEjer14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyPressEjer14(evt);
            }
        });
        jPanel11.add(txtDigiteEjer14);
        txtDigiteEjer14.setBounds(10, 100, 259, 22);

        jLabel54.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Su resultado es");
        jPanel11.add(jLabel54);
        jLabel54.setBounds(10, 140, 130, 20);
        jPanel11.add(lblResultadoEjer14);
        lblResultadoEjer14.setBounds(10, 180, 259, 22);

        btnCalcularEjer14.setText("Calcular");
        btnCalcularEjer14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularEjer14ActionPerformed(evt);
            }
        });
        jPanel11.add(btnCalcularEjer14);
        btnCalcularEjer14.setBounds(150, 240, 100, 30);

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciostaller/14.gif"))); // NOI18N
        jLabel64.setText("jLabel64");
        jPanel11.add(jLabel64);
        jLabel64.setBounds(-7, 6, 590, 380);

        jTabbedPane1.addTab("Ejercicio 14", jPanel11);

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setLayout(null);

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Calcular la hipotenusa de un triangulo  ");
        jPanel13.add(jLabel14);
        jLabel14.setBounds(10, 20, 470, 22);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Digite el valor del cateto 1");
        jPanel13.add(jLabel16);
        jLabel16.setBounds(10, 50, 200, 15);

        txtCateto1Ejer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCateto1Ejer7ActionPerformed(evt);
            }
        });
        txtCateto1Ejer7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Keypresscateto1(evt);
            }
        });
        jPanel13.add(txtCateto1Ejer7);
        txtCateto1Ejer7.setBounds(10, 80, 160, 22);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Digite el valor del cateto 2");
        jPanel13.add(jLabel17);
        jLabel17.setBounds(10, 120, 190, 15);

        txtCateto2Ejer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCateto2Ejer7ActionPerformed(evt);
            }
        });
        txtCateto2Ejer7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Keypressresull(evt);
            }
        });
        jPanel13.add(txtCateto2Ejer7);
        txtCateto2Ejer7.setBounds(10, 150, 160, 22);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("El resultado de la hipotenusa es igual a:");
        jPanel13.add(jLabel18);
        jLabel18.setBounds(10, 210, 290, 15);

        lblResultadoEjer7.setText("0");
        jPanel13.add(lblResultadoEjer7);
        lblResultadoEjer7.setBounds(10, 240, 337, 22);

        btnCalcularHipotenusaEjer7.setBackground(new java.awt.Color(255, 204, 51));
        btnCalcularHipotenusaEjer7.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularHipotenusaEjer7.setText("Calcular la hipotenusa ");
        btnCalcularHipotenusaEjer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularHipotenusaEjer7ActionPerformed(evt);
            }
        });
        jPanel13.add(btnCalcularHipotenusaEjer7);
        btnCalcularHipotenusaEjer7.setBounds(20, 310, 180, 23);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciostaller/7.1.gif"))); // NOI18N
        jPanel13.add(jLabel47);
        jLabel47.setBounds(0, 0, 580, 390);

        jTabbedPane1.addTab("Ejercicio 7", jPanel13);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html>Se ingresa el valor de 8 digitos<center> donde se ordene donde como una fecha\n");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 10, 300, 40);

        jLabel6.setBackground(new java.awt.Color(0, 204, 204));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ingrese un valor maximo de 8 digitos(año/mes/dia) ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 70, 290, 16);

        txtNumeroEjer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroEjer5ActionPerformed(evt);
            }
        });
        txtNumeroEjer5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroEjer5(evt);
            }
        });
        jPanel2.add(txtNumeroEjer5);
        txtNumeroEjer5.setBounds(10, 110, 280, 22);

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("El resultado de su valor en dia/mes /año");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 140, 260, 20);
        jPanel2.add(lblResultadoEjer5);
        lblResultadoEjer5.setBounds(10, 170, 280, 22);

        btnCalcularEjer5.setText("Calcular");
        btnCalcularEjer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularEjer5ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalcularEjer5);
        btnCalcularEjer5.setBounds(30, 220, 150, 23);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciostaller/5.1.gif"))); // NOI18N
        jPanel2.add(jLabel42);
        jLabel42.setBounds(0, 0, 580, 390);

        jTabbedPane1.addTab("Ejercicio 5 ", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setMaximumSize(new java.awt.Dimension(400, 400));
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("TerminessTTF NF", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html>Se leen tres valores en donde se indica<center> cual es el mayor el del medio y el menor ");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(320, 10, 190, 100);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ingrese el primer numero");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(0, 60, 180, 16);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ingrese el segundo numero");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(0, 128, 180, 16);

        txtNumero1Ejer6.setBackground(new java.awt.Color(153, 255, 204));
        txtNumero1Ejer6.setForeground(new java.awt.Color(0, 0, 0));
        txtNumero1Ejer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero1Ejer6ActionPerformed(evt);
            }
        });
        txtNumero1Ejer6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyPressN1(evt);
            }
        });
        jPanel3.add(txtNumero1Ejer6);
        txtNumero1Ejer6.setBounds(0, 88, 164, 22);

        txtNumero2Ejer6.setBackground(new java.awt.Color(153, 255, 204));
        txtNumero2Ejer6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressN2(evt);
            }
        });
        jPanel3.add(txtNumero2Ejer6);
        txtNumero2Ejer6.setBounds(0, 162, 164, 22);
        jPanel3.add(jLabel11);
        jLabel11.setBounds(249, 274, 0, 0);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ingrese el tercer numero");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(0, 202, 170, 16);

        txtNumero3Ejer6.setBackground(new java.awt.Color(153, 255, 204));
        txtNumero3Ejer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero3Ejer6ActionPerformed(evt);
            }
        });
        txtNumero3Ejer6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyPressN3(evt);
            }
        });
        jPanel3.add(txtNumero3Ejer6);
        txtNumero3Ejer6.setBounds(0, 236, 164, 22);

        btnCalcularEjer6.setForeground(new java.awt.Color(204, 0, 0));
        btnCalcularEjer6.setText("Calcular ");
        btnCalcularEjer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularEjer6ActionPerformed(evt);
            }
        });
        jPanel3.add(btnCalcularEjer6);
        btnCalcularEjer6.setBounds(191, 280, 120, 23);
        jPanel3.add(jLabel13);
        jLabel13.setBounds(249, 449, 0, 0);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Su resultado es");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(0, 333, 140, 16);

        lblResultadoEjer6.setBackground(new java.awt.Color(153, 255, 204));
        lblResultadoEjer6.setText("0");
        jPanel3.add(lblResultadoEjer6);
        lblResultadoEjer6.setBounds(0, 367, 300, 22);

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciostaller/8.gif"))); // NOI18N
        jLabel62.setText("jLabel62");
        jPanel3.add(jLabel62);
        jLabel62.setBounds(-190, -30, 960, 540);

        jTabbedPane1.addTab("Ejercicio 6", jPanel3);

        jPanel10.setBackground(new java.awt.Color(255, 255, 204));
        jPanel10.setLayout(null);

        jLabel35.setBackground(new java.awt.Color(204, 204, 204));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("<html>Se recibe como entrada un carácter y de cómo salida el número de  <center>ocurrencias de dicho carácter en una cadena de caracteres.");
        jPanel10.add(jLabel35);
        jLabel35.setBounds(30, 0, 440, 90);

        jLabel49.setBackground(new java.awt.Color(204, 204, 204));
        jLabel49.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Ingrese un caracter:");
        jPanel10.add(jLabel49);
        jLabel49.setBounds(70, 160, 160, 30);

        txtEjer13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEjer13ActionPerformed(evt);
            }
        });
        txtEjer13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyPressEjer13(evt);
            }
        });
        jPanel10.add(txtEjer13);
        txtEjer13.setBounds(120, 210, 220, 30);

        jLabel50.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Su resultado de los caracteres es:");
        jPanel10.add(jLabel50);
        jLabel50.setBounds(60, 250, 200, 40);
        jPanel10.add(jLabel51);
        jLabel51.setBounds(454, 254, 0, 0);
        jPanel10.add(jLabel52);
        jLabel52.setBounds(169, 276, 158, 0);

        lblResultadoejer13.setBackground(new java.awt.Color(255, 255, 255));
        lblResultadoejer13.setForeground(new java.awt.Color(0, 0, 0));
        lblResultadoejer13.setText("0");
        lblResultadoejer13.setOpaque(true);
        jPanel10.add(lblResultadoejer13);
        lblResultadoejer13.setBounds(120, 290, 185, 25);

        btnBoton.setText("Calcular");
        btnBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotonActionPerformed(evt);
            }
        });
        jPanel10.add(btnBoton);
        btnBoton.setBounds(350, 340, 90, 30);

        jLabel60.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 0, 0));
        jLabel60.setText("Digite el caracter las veces que desee calcular");
        jPanel10.add(jLabel60);
        jLabel60.setBounds(30, 70, 260, 50);

        txtVecesEjer13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVecesEjer13ActionPerformed(evt);
            }
        });
        txtVecesEjer13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyPressSaltoEjer13(evt);
            }
        });
        jPanel10.add(txtVecesEjer13);
        txtVecesEjer13.setBounds(120, 120, 260, 30);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciostaller/11.gif"))); // NOI18N
        jPanel10.add(jLabel59);
        jLabel59.setBounds(100, 10, 600, 380);

        jTabbedPane1.addTab("Ejercicio 13", jPanel10);

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setLayout(null);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("<html>Se digitara una frase minimo de 5 <center> palabras donde se capitalizar la cadena");
        jPanel12.add(jLabel38);
        jLabel38.setBounds(10, 0, 410, 50);

        jLabel57.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Ingrese la frase de 5 palabras ");
        jPanel12.add(jLabel57);
        jLabel57.setBounds(20, 50, 200, 30);

        txtFraseEjer16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFraseEjer16ActionPerformed(evt);
            }
        });
        txtFraseEjer16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyPressEjer16(evt);
            }
        });
        jPanel12.add(txtFraseEjer16);
        txtFraseEjer16.setBounds(10, 90, 190, 22);

        jLabel58.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Su resultado es");
        jPanel12.add(jLabel58);
        jLabel58.setBounds(20, 130, 130, 30);

        lblResultadoEjer16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblResultadoEjer16ActionPerformed(evt);
            }
        });
        jPanel12.add(lblResultadoEjer16);
        lblResultadoEjer16.setBounds(10, 180, 200, 22);

        btnCalcularEjer16.setText("Calcular");
        btnCalcularEjer16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularEjer16ActionPerformed(evt);
            }
        });
        jPanel12.add(btnCalcularEjer16);
        btnCalcularEjer16.setBounds(60, 250, 80, 30);

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciostaller/88.gif"))); // NOI18N
        jPanel12.add(jLabel65);
        jLabel65.setBounds(-150, 0, 730, 390);

        jTabbedPane1.addTab("Ejercicio 16", jPanel12);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    public boolean isNumber(String numero) {
        try {
            int Number = Integer.parseInt(numero);
            return true;
        } catch (NumberFormatException NFE) {
            JOptionPane.showMessageDialog(this,
                    "El texto " + numero + " no es un numero valido",
                    "Numero Invalido", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    public void numerovariable() {
        try {
            if (txtnumeroejer4.getText().equalsIgnoreCase("0") || txtnumeroejer4.getText().substring(1, 1) == "-") {
                JOptionPane.showMessageDialog(this, "Ingrese un valor valido", "Valor Incorrecto", JOptionPane.ERROR_MESSAGE);
                txtnumeroejer4.setText("");
            } else {
                if (isNumber(txtnumeroejer4.getText()));

                int Number = Integer.parseInt(txtnumeroejer4.getText());
                if (Number > 0) {
                    lblesultadosejer4.setText((Number % 3 == 0 && Number % 2 == 0) ? "Si es multiplo de 2 y 3" : "No es multiplo de 2 y 3");
                    lblesultadosejer4.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Ingrese un valor valido", "Valor Incorrecto", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
        }

    }

    public void ejercicio5() {
        try {
            int anio = 0;
            int dia = 0;
            int mes = 0;
            if (anio >= 0 && mes >= 0 && dia >= 0) {
                if (!(txtNumeroEjer5.getText().length() == 8) || (txtNumeroEjer5.getText().substring(1, 1) == "-")) {
                    JOptionPane.showMessageDialog(this, "Ingrese un valor valido", "Valor Incorrecto", JOptionPane.ERROR_MESSAGE);
                    txtNumeroEjer5.setText("");

                } else {
                    if (isNumber(txtNumeroEjer5.getText()));
                    int x = Integer.parseInt(txtNumeroEjer5.getText());
                    anio = x / 10000;
                    mes = (x % 10000) / 100;
                    dia = x % 100;
                    lblResultadoEjer5.setText("año " + anio + "\n mes " + mes + " dia " + dia);
                    lblResultadoEjer5.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "Los numeros deben ser positivos",
                        "Numero NO Invalido", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
        }

    }

    public void ejercicio6() {
        try {
            int n1 = 0, n2 = 0, n3 = 0, Mayor = 0, Menor = 0, Medio = 0;
            String texto = "";
            if (isNumber(txtNumero1Ejer6.getText()) && isNumber(txtNumero2Ejer6.getText()) && isNumber(txtNumero3Ejer6.getText())) {
                n1 = Integer.parseInt(txtNumero1Ejer6.getText());
                n2 = Integer.parseInt(txtNumero2Ejer6.getText());
                n3 = Integer.parseInt(txtNumero3Ejer6.getText());
                if (n1 >= 0 && n2 >= 0 && n3 >= 0) {
                    Mayor = ((n1 > n2 && n1 > n3) ? n1 : (n2 > n1 && n2 > n3) ? n2 : n3);
                    Menor = ((n1 < n2 && n1 < n3) ? n1 : (n2 < n1 && n2 < n3) ? n2 : n3);
                    if ((n1 == Mayor || n1 == Menor) && (n2 == Menor || n2 == Mayor)) {
                        Medio = n3;
                    } else if ((n1 == Mayor || n1 == Menor) && (n3 == Menor || n3 == Mayor)) {
                        Medio = n2;
                    } else if ((n2 == Mayor || n2 == Menor) && (n3 == Menor || n3 == Mayor)) {
                        Medio = n1;
                    }
                    lblResultadoEjer6.setText("Mayor= " + Mayor + ", Medio= " + Medio + ", Menor= " + Menor);
                    lblResultadoEjer6.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Los numeros deben ser positivos",
                            "Numero NO Invalido", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
        }

    }

    public void ejercicio7() {
        try {
            if (isNumber(txtCateto1Ejer7.getText()) && isNumber(txtCateto2Ejer7.getText())) {
                double cateto1 = Double.parseDouble(txtCateto1Ejer7.getText());
                double cateto2 = Double.valueOf(txtCateto2Ejer7.getText());
                if (cateto1 > 0 && cateto2 > 0) {
                    cateto1 = Integer.parseInt(txtCateto1Ejer7.getText());
                    cateto2 = Integer.parseInt(txtCateto2Ejer7.getText());
                    double resultado = Double.valueOf(lblResultadoEjer7.getText());
                    resultado = Math.sqrt(Math.pow(cateto1, 2) + Math.pow(cateto2, 2));
                    lblResultadoEjer7.setText("La hipotenusa es igual a:" + resultado);
                    lblResultadoEjer7.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Ingrese un valor valido", "Valor Incorrecto", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
        }

    }

    public void ejercicio8() {
        if (!(txtFecha1Ejer8.getText().length() == 8) || (txtFecha1Ejer8.getText().substring(1, 1) == "-")) {
            JOptionPane.showMessageDialog(this, "Ingrese el valor que sea valido", "Valor Incorrecto", JOptionPane.ERROR_MESSAGE);
            txtFecha1Ejer8.setText("");
        } else {
            if (isNumber(txtFecha1Ejer8.getText())) {
                int x = Integer.parseInt(txtFecha1Ejer8.getText());
                int anio = (x / 10000);
                int mes = (x % 10000 / 100);
                int dia = (x % 100);

                if ((anio <= 2023) && (mes >= 1 && mes <= 12) && (dia >= 1 && dia <= 31)) {
                    if ((mes == 4 || mes == 6 || mes == 9 || mes == 11) && (dia >= 1 && dia <= 30)) {
                        lblValidacionEjer8.setText("El año es:" + anio + "El mes es:" + mes + "El dia es:" + dia);
                        lblValidacionEjer8.setVisible(true);
                    } else if (!(mes == 4 || mes == 6 || mes == 9 || mes == 11) && (dia >= 1 && dia <= 31)) {
                        lblValidacionEjer8.setText("El año es:" + anio + "El mes es:" + mes + "El dia es:" + dia);
                        lblValidacionEjer8.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(this,
                                "Los numeros deben deben de estar dentro del rango del año, mes y dia vigente",
                                "Numero NO Invalido", JOptionPane.ERROR_MESSAGE);;
                    }
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Los numeros deben deben de estar dentro del rango del año, mes y dia vigente",
                            "Numero NO Invalido", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    public void ejercicio9() {
        try {
            int numero = 0;
            numero = Integer.parseInt(txtNumero1Ejer9.getText());
            if (numero >= 1 && numero <= 12) {
                String mes = null;
                switch (numero) {
                    case 1:
                        mes = "Enero";
                        break;
                    case 2:
                        mes = "Febrero";
                        break;
                    case 3:
                        mes = "Marzo";
                        break;
                    case 4:
                        mes = "Abril";
                        break;
                    case 5:
                        mes = "Mayo";
                        break;
                    case 6:
                        mes = "Junio";
                        break;
                    case 7:
                        mes = "Julio";
                        break;
                    case 8:
                        mes = "Agosto";
                        break;
                    case 9:
                        mes = "Septiembre";
                        break;
                    case 10:
                        mes = "Octubre";
                        break;
                    case 11:
                        mes = "Noviembre";
                        break;
                    case 12:
                        mes = "Diciembre";
                        break;
                    default:
                        break;
                }
                lblResultadomesEjer9.setText("El mes correspondiente es: " + mes);
                lblResultadomesEjer9.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Los numeros deben deben de estar dentro del rango",
                        "Numero NO Invalido", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Deben de ser numero enteros",
                    "Numero NO Invalido", JOptionPane.ERROR_MESSAGE);

        }
    }

    public void ejercicio10() {
        try {
            int segundos10 = 0, horas10 = 0, minutos10 = 0;

            int numero10 = Integer.parseInt(txtNumero1Ejer10.getText());
            if (numero10 > 0) {
                segundos10 = numero10;
                horas10 = segundos10 / 3600;
                minutos10 = (segundos10 / 60);
                lblResultadoEjer10.setText("los segundos: " + segundos10 + " Los minutos: " + minutos10 + " Las horas:" + horas10);
                lblResultadoEjer10.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Digite numeros validos",
                        "Numero NO Invalido", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Digite valores validos, como se piden:((",
                    "Numero NO Invalido", JOptionPane.ERROR_MESSAGE);

        }
    }

    public void ejercicio11() {
        try {
            long numEjer10 = 0;
            int numero11 = 0, resto, invertido = 0;
            if (("-".equals(txtNumero1Ejer11.getText().substring(1, 1)))) {
                JOptionPane.showMessageDialog(this, "Ingrese el valor que sea valido", "Valor Incorrecto", JOptionPane.ERROR_MESSAGE);
                txtNumero1Ejer11.setText("");
            } else {
                if (isNumber(txtNumero1Ejer11.getText()));
                numEjer10 = Long.parseLong(txtNumero1Ejer11.getText());
                String numeroStr = String.valueOf(numEjer10);
                String con = "";
                if (numEjer10 > 0) {
                    for (int i = numeroStr.length() - 1; i >= 0; i--) {
                        numero11 = Character.getNumericValue(numeroStr.charAt(i));
                        con = con + numero11;
                    }
                    lblResultadoEjer11.setText("La inversa es: " + con);
                } else {
                    JOptionPane.showMessageDialog(this, "Ingrese el valor que sea valido", "Valor Incorrecto", JOptionPane.ERROR_MESSAGE);
                }
                lblResultadoEjer11.setVisible(true);

            }
        } catch (NumberFormatException e) {
        }
    }

    public void ejercicio12() {
        if (isNumber(txtNumero1Ejer12.getText())) {

            int numero = Integer.parseInt(txtNumero1Ejer12.getText());
            if (numero > 0) {
                if (numero % 2 == 0) {
                    lblParEjer12.setText("el numero" + " " + numero + " " + "es par ");

                } else {

                    lblParEjer12.setText("el numero" + " " + numero + " " + "es impar ");
                }

                if (capicua(numero)) {
                    lblParCapicuoEjer12.setText("el numero" + " " + numero + " " + "es capicua");

                } else {
                    lblParCapicuoEjer12.setText("el numero" + " " + numero + " " + "no es capicua");

                }
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese el valor que sea valido", "Valor Incorrecto", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public static boolean capicua(int numero12) {
        int numeroveces = 0;
        int digito1 = numero12;

        while (numero12 != 0) {
            int digito = numero12 % 10;
            numeroveces = numeroveces * 10 + digito;
            numero12 /= 10;
        }
        return digito1 == numeroveces;
    }

    public void ejercicio13() {
        String cadena = txtEjer13.getText();
        char caracter1 = txtVecesEjer13.getText().charAt(0);
        int contador = calcular(cadena, caracter1);
        lblResultadoejer13.setText("El carácter '" + caracter1 + "' aparece " + contador + " veces.");
        lblResultadoejer13.setVisible(true);
    }

    public static int calcular(String cadena, char caracter2) {
        int contador = 0;
        for (int i = 0; i < cadena.length(); i++) {
            if (cadena.charAt(i) == caracter2) {
                contador++;
            }
        }
        return contador;
    }

    public void ejercicio14() {
        if (isNumber(txtDigiteEjer14.getText())) {
            int num = Integer.parseInt(txtDigiteEjer14.getText());
            if (num < 0) {
                JOptionPane.showMessageDialog(this,
                        "Numero invalido, ingrese numeros validos:)", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtDigiteEjer14.setText("");
            } else {
                String digito = txtDigiteEjer14.getText();

                if (Palindroma(digito)) {
                    lblResultadoEjer14.setText("La cadena es un palíndromo.");
                } else {
                    lblResultadoEjer14.setText("La cadena no es un palíndromo.");
                }
                lblResultadoEjer14.setVisible(true);
            }

        }
    }

    public static boolean Palindroma(String digito) {
        digito = digito.replaceAll("", "").toLowerCase();
        int a = 0;
        int b = digito.length() - 1;
        while (a < b) {
            if (digito.charAt(a) != digito.charAt(b)) {
                return false;
            }
            a++;
            b--;
        }
        return true;
    }

    public void ejercicio15() {
        if (isNumber(txtNumeroEjer15.getText())) {
            int num = Integer.parseInt(txtNumeroEjer15.getText());
            if (num < 0 || num > 99) {
                JOptionPane.showMessageDialog(this,
                        "Numero invalido, ingrese numero que este ene rango de 0 a 99", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtNumeroEjer15.setText("");
            } else {
                String digito = conversion(num);
                lblResultadoEjer15.setText("" + num + " En palabras: " + digito);
                lblResultadoEjer15.setVisible(true);
            }
        }
    }

    public static String conversion(int num) {
        String[] unidades = {"cero", "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve"};
        String[] decenas = {"diez", "once", "doce", "trece", "catorce", "quince", "dieciseis", "diecisiete", "dieciocho", "diecinueve"};
        String[] centenas = {"", "", "veinte", "treinta", "cuarenta", "cincuenta", "sesenta", "setenta", "ochenta", "noventa"};
        if (num < 10) {
            return unidades[num];
        } else if (num >= 10 && num < 20) {
            return decenas[num - 10];
        } else {
            int decena = num / 10;
            int unidad = num % 10;
            String resultado = decenas[decena];
            if (unidad > 0) {
                resultado += " y " + unidades[unidad];
            }
            return resultado;
        }
    }

    public void ejercicio16() {
        String frase = txtFraseEjer16.getText();
        if (cadena(frase) >= 5) {
            String fraseCapitalizada = capitalizar(frase);
            lblResultadoEjer16.setText("Frase capitalizada: " + fraseCapitalizada);

        } else {
            JOptionPane.showMessageDialog(this,
                        "Digite una frase de minimo 5 palabras",
                        "Numero NO Invalido", JOptionPane.ERROR_MESSAGE);
            txtFraseEjer16.setText("");
        }
        lblResultadoEjer16.setVisible(true);
    }

    public static int cadena(String frase) {
        if (frase == null || frase.isEmpty()) {
            return 0;
        }
        String[] num1 = frase.trim().split("\\s+");
        return num1.length;
    }

    public static String capitalizar(String frase) {
        if (frase == null || frase.isEmpty()) {
            return "";
        }
        String[] caracteres = frase.trim().split("\\s+");
        StringBuilder charter = new StringBuilder();
        for (String palabra : caracteres) {
            char linea = Character.toUpperCase(palabra.charAt(0));
            charter.append(linea).append(palabra.substring(1)).append(" ");
        }
        return charter.toString().trim();
    }

    private void txtFecha1Ejer8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecha1Ejer8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecha1Ejer8ActionPerformed

    private void lblResultadoEjer10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblResultadoEjer10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblResultadoEjer10ActionPerformed

    private void lblResultadoEjer11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblResultadoEjer11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblResultadoEjer11ActionPerformed

    private void txtCateto1Ejer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCateto1Ejer7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCateto1Ejer7ActionPerformed

    private void txtCateto2Ejer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCateto2Ejer7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCateto2Ejer7ActionPerformed

    private void btnCalcularHipotenusaEjer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularHipotenusaEjer7ActionPerformed
        ejercicio7();    }//GEN-LAST:event_btnCalcularHipotenusaEjer7ActionPerformed

    private void btnCalcularEjer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularEjer5ActionPerformed
        ejercicio5();    }//GEN-LAST:event_btnCalcularEjer5ActionPerformed

    private void txtnumeroejer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroejer4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroejer4ActionPerformed

    private void btnejer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnejer4ActionPerformed
        numerovariable();
    }//GEN-LAST:event_btnejer4ActionPerformed

    private void txtNumeroEjer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroEjer5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroEjer5ActionPerformed

    private void lblesultadosejer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblesultadosejer4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblesultadosejer4ActionPerformed

    private void txtNumero1Ejer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero1Ejer6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero1Ejer6ActionPerformed

    private void btnCalcularEjer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularEjer6ActionPerformed
        ejercicio6();
    }//GEN-LAST:event_btnCalcularEjer6ActionPerformed

    private void btnValidarResultadoEjer8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarResultadoEjer8ActionPerformed
        ejercicio8();    }//GEN-LAST:event_btnValidarResultadoEjer8ActionPerformed

    private void btnCalcularEjer9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularEjer9ActionPerformed
        ejercicio9();    }//GEN-LAST:event_btnCalcularEjer9ActionPerformed

    private void KeyPressN1(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyPressN1
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNumero2Ejer6.grabFocus();
        }
    }//GEN-LAST:event_KeyPressN1

    private void btnCalcularEjer10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularEjer10ActionPerformed
        ejercicio10();    }//GEN-LAST:event_btnCalcularEjer10ActionPerformed

    private void btnCalcularEjer11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularEjer11ActionPerformed
        ejercicio11();    }//GEN-LAST:event_btnCalcularEjer11ActionPerformed

    private void txtnumeroejer4(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroejer4

     }//GEN-LAST:event_txtnumeroejer4

    private void kaypreseejer4(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kaypreseejer4
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            numerovariable();}    }//GEN-LAST:event_kaypreseejer4

    private void txtNumeroEjer5(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroEjer5
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ejercicio5();}    }//GEN-LAST:event_txtNumeroEjer5

    private void keyPressN2(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressN2
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNumero3Ejer6.grabFocus();
        }    }//GEN-LAST:event_keyPressN2

    private void txtNumero3Ejer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero3Ejer6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero3Ejer6ActionPerformed

    private void KeyPressN3(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyPressN3
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ejercicio6();
        }
    }//GEN-LAST:event_KeyPressN3

    private void Keypresscateto1(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Keypresscateto1
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtCateto2Ejer7.grabFocus();    }//GEN-LAST:event_Keypresscateto1
    }
    private void Keypressresull(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Keypressresull
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ejercicio7();    }//GEN-LAST:event_Keypressresull
    }
    private void Keypress1Ejer8(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Keypress1Ejer8
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ejercicio8();
    }//GEN-LAST:event_Keypress1Ejer8
    }
    private void Keypressejer9(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Keypressejer9
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ejercicio9();    }//GEN-LAST:event_Keypressejer9
    }
    private void KeypressEjer10(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeypressEjer10
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ejercicio10();    }//GEN-LAST:event_KeypressEjer10
    }
    private void KeypressEjer11(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeypressEjer11
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ejercicio11();    }//GEN-LAST:event_KeypressEjer11
        }
    private void txtEjer13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEjer13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEjer13ActionPerformed

    private void btnBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotonActionPerformed
        ejercicio13();
    }//GEN-LAST:event_btnBotonActionPerformed

    private void btnCalcularEjer14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularEjer14ActionPerformed
        ejercicio14();
    }//GEN-LAST:event_btnCalcularEjer14ActionPerformed

    private void lblResultadoEjer15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblResultadoEjer15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblResultadoEjer15ActionPerformed

    private void btnBotonEjer15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotonEjer15ActionPerformed
        ejercicio15();    }//GEN-LAST:event_btnBotonEjer15ActionPerformed

    private void txtFraseEjer16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFraseEjer16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFraseEjer16ActionPerformed

    private void lblResultadoEjer16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblResultadoEjer16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblResultadoEjer16ActionPerformed

    private void btnCalcularEjer16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularEjer16ActionPerformed
        ejercicio16();    }//GEN-LAST:event_btnCalcularEjer16ActionPerformed

    private void KeyPressEjer15(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyPressEjer15
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ejercicio15();
        }     }//GEN-LAST:event_KeyPressEjer15

    private void KeyPressEjer14(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyPressEjer14
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ejercicio14();}    }//GEN-LAST:event_KeyPressEjer14

    private void KeyPressEjer13(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyPressEjer13
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ejercicio13();
        }     }//GEN-LAST:event_KeyPressEjer13

    private void KeyPressEjer16(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyPressEjer16
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ejercicio16();
        }     }//GEN-LAST:event_KeyPressEjer16

    private void txtVecesEjer13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVecesEjer13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVecesEjer13ActionPerformed

    private void KeyPressSaltoEjer13(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyPressSaltoEjer13
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtEjer13.grabFocus();
        }     }//GEN-LAST:event_KeyPressSaltoEjer13

    private void lblResultadomesEjer9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblResultadomesEjer9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblResultadomesEjer9ActionPerformed

    private void btnCalcularEjer12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularEjer12ActionPerformed
        // TODO add your handling code here:
        ejercicio12();
    }//GEN-LAST:event_btnCalcularEjer12ActionPerformed

    private void KeypressEjer12(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeypressEjer12
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             ejercicio12();
        }
    }//GEN-LAST:event_KeypressEjer12

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejer_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejer_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejer_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejer_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejer_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btnBoton;
    private javax.swing.JButton btnBotonEjer15;
    private javax.swing.JButton btnCalcularEjer10;
    private javax.swing.JButton btnCalcularEjer11;
    private javax.swing.JButton btnCalcularEjer12;
    private javax.swing.JButton btnCalcularEjer14;
    private javax.swing.JButton btnCalcularEjer16;
    private javax.swing.JButton btnCalcularEjer5;
    private javax.swing.JButton btnCalcularEjer6;
    private javax.swing.JButton btnCalcularEjer9;
    private javax.swing.JButton btnCalcularHipotenusaEjer7;
    private javax.swing.JButton btnValidarResultadoEjer8;
    private javax.swing.JButton btnejer4;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lblParCapicuoEjer12;
    private javax.swing.JTextField lblParEjer12;
    private javax.swing.JTextField lblResultadoEjer10;
    private javax.swing.JTextField lblResultadoEjer11;
    private javax.swing.JTextField lblResultadoEjer14;
    private javax.swing.JTextField lblResultadoEjer15;
    private javax.swing.JTextField lblResultadoEjer16;
    private javax.swing.JTextField lblResultadoEjer5;
    private javax.swing.JTextField lblResultadoEjer6;
    private javax.swing.JTextField lblResultadoEjer7;
    private javax.swing.JLabel lblResultadoejer13;
    private javax.swing.JTextField lblResultadomesEjer9;
    private javax.swing.JTextField lblValidacionEjer8;
    private javax.swing.JTextField lblesultadosejer4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTextField txtCateto1Ejer7;
    private javax.swing.JTextField txtCateto2Ejer7;
    private javax.swing.JTextField txtDigiteEjer14;
    private javax.swing.JTextField txtEjer13;
    private javax.swing.JTextField txtFecha1Ejer8;
    private javax.swing.JTextField txtFraseEjer16;
    private javax.swing.JTextField txtNumero1Ejer10;
    private javax.swing.JTextField txtNumero1Ejer11;
    private javax.swing.JTextField txtNumero1Ejer12;
    private javax.swing.JTextField txtNumero1Ejer6;
    private javax.swing.JTextField txtNumero1Ejer9;
    private javax.swing.JTextField txtNumero2Ejer6;
    private javax.swing.JTextField txtNumero3Ejer6;
    private javax.swing.JTextField txtNumeroEjer15;
    private javax.swing.JTextField txtNumeroEjer5;
    private javax.swing.JTextField txtVecesEjer13;
    private javax.swing.JTextField txtnumeroejer4;
    // End of variables declaration//GEN-END:variables

}
